version: '3'

services:
  dev_db:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'database_development'
      POSTGRES_PASSWORD: 'postgres'

  s3:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - "6379:6379"